#SPDX-License-Identifier: MIT-0
---
# tasks file for apache-webserver

- name: Install apache webserver pkgs
  package:
    name: "{{ item }}"
    state: latest
  with_items:
   - apache2
   - apache2-data
   - apache2-utils
   - apache2-doc

- name: Remove default apache web site
  file:
    path: "{{ apache_default_site }}"
    state: 'absent'
  handlers: 'apache_service_reload'

- name: Enable apache webserver modules
  apache2_module:
    name: "{{ }}"
    present: 'present'
  tag: wordpress_modules
  with_items:
   - 
   -
   -

- name: Enable and start apache service
  service:
    name: 'apache2'
    state: "{{ item }}"
  with_items:
   - enabled
   - start